baseurl = "https://ericingland.com/"
languageCode = "en-US"
title = "Eric Ingland - Systems Administrator and Software Developer"
# Enable comments by entering your Disqus shortname
disqusShortname = "eric-ingland-blog"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-54604214-6"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpg"
  author = "Eric Ingland"
  description = "Personal and Technical Blog"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "eingland"
  Email         = "ingland.eric@gmail.com"
  Twitter       = "ericingland"
  LinkedIn      = "ericingland"
  Stackoverflow = "users/9735692/eric-ingland"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/media/resume.pdf"
